import Head from 'next/head'
import Authentication from '../components/form-layout';
import Image from 'next/image'
import Img from '/image/images.jpg'

export const StepOne = () => {
  return (
    <form className="w-screen">
      <div className="flex">
          <div className="w-1/2">
              <Image src={Img} alt="form-image"/>
          </div>
        <div className="w-full h-screen bg-gray-500">
          <div className="bg-red-500 m-10 h-5/6">
            <div className="flex p-10">
              <p>Sign Up</p>
              <p className="ml-5">Message</p>
              <p className="ml-5">Checkbox</p>
            </div>
          </div>
        </div>    
        </div>
    </form>
  )
}

export const StepTwo = () => {
  return (
    <form>
        <div>
            <Image src={Img} alt="form-image" 
            />
        </div>
        <div>
          {/* Step */}
      </div>
      <form>
        {/* content */}
        {/* button */}
      </form>
    </form>
  )
}

export const StepThree = () => {
  return (
    <form>
        <div>
            <Image src={Img} alt="form-image" 
            />
        </div>
        <div>
          {/* step */}
      </div>
      <form>
        {/* content */}
        {/* button */}
      </form>
    </form>
  )
}

export default function Home() {
  return (
    <Authentication>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
          <StepOne/>
          
        </div>
      </Authentication>
  )
}
