import Head from 'next/head'
import Authentication from '../components/form-layout';
import Image from 'next/image'
import Img from '/image/images.jpg'
import DateSection from '../components/date/Date';
// import { faCalendar } from '@fortawesome/free-solid-svg-icons'
// import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

export const StepOne = () => {
  return (
    <form className="w-screen">
      <div className="flex">
          <div className="w-1/2 mt-40 hidden md:block">
              <Image src={Img} alt="form-image"/>
          </div>
        <div className="w-full h-screen bg-cyan-700">
          <div className="m-10 h-5/6">
            <h1 className="text-center text-white font-semibold text-7xl">Sign UP</h1>

            <div className="flex mt-20 text-white justify-center items-center w-100">
                <div className="mr-10">
                  <p>First Name</p>
                  <input type="text" className='p-4 mt-3 rounded-xl inline-transparent focus:outline-transparent'/>
                </div>
                <div className="">
                  <p>Last Name</p>
                  <input type="text" className='p-4 mt-3 rounded-xl'/>
                </div>  
            </div>

            <div className="flex mt-10 text-white justify-center items-center w-100">
                <div className="mr-10">
                  <p>Date of Birth</p>
                  <div className="datepicker relative form-floating mb-3 xl:w-96 flex items-center justify-center" data-mdb-toggle-button="false">
                    <input type="text"
                      className="form-control p-2 text-base font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none"
                      placeholder="Select a date" />
                    <button className="datepicker-toggle-button w-20" data-mdb-toggle="datepicker">
                        {/* <FontAwesomeIcon icon={faCalendar} className="fa-2xs"/> */}
                        
                  </button>
                  <DateSection/>
                </div>
                </div>
                <div className="">
                  <p>Email Address</p>
                  <input type="text" className='p-4 mt-3 rounded-xl'/>
                </div>  
            </div>
          </div>
        </div>    
        </div>
    </form>
  )
}

export const StepTwo = () => {
  return (
    <form>
        <div>
            <Image src={Img} alt="form-image" 
            />
        </div>
        <div>
          {/* Step */}
      </div>
      <form>
        {/* content */}
        {/* button */}
      </form>
    </form>
  )
}

export const StepThree = () => {
  return (
    <form>
        <div>
            <Image src={Img} alt="form-image" 
            />
        </div>
        <div>
          {/* step */}
      </div>
      <form>
        {/* content */}
        {/* button */}
      </form>
    </form>
  )
}

export default function Home() {
  return (
    <Authentication>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet"></link>
        </Head>
          <StepOne/>
          
        </div>
      </Authentication>
  )
}
