import Head from 'next/head'
import Authentication from '../components/form-layout';
import Image from 'next/image'
import Img from '/image/images.jpg'
import DateSection from '../components/date/Date';
// import { faCalendar } from '@fortawesome/free-solid-svg-icons'
// import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

export const StepOne = () => {
  return (
    <form className="w-screen">
      <div className="flex">
          <div className="w-1/2 mt-40 hidden md:block">
              <Image src={Img} alt="form-image"/>
          </div>
        <div className="w-full h-screen bg-cyan-700">
          <div className="m-10 h-5/6">
            <span className="text-center font-semibold text-7xl before:block before:absolute before:-inset-1 before:-skew-y-3 before:bg-cyan-900 relative inline-block left-1/3">
              <span className="text-white relative">
                  Sign UP
              </span>
            </span>

            <div className="flex mt-20 justify-center items-center w-100">
                <div className="mr-10">
                  <p className="text-white font-semibold">First Name</p>
                <input type="text" className='w-60 h-14 p-2 mt-3 rounded-xl inline-transparent focus:outline-transparent
                  border-solid border-gray-300 transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none
                  '/>
                </div>
                <div className="">
                  <p className="text-white font-semibold">Last Name</p>
                  <input type="text" className='w-60 h-14 p-2 mt-3 rounded-xl'/>
                </div>  
            </div>

            <div className="flex mt-10 justify-center items-center w-100">
                <div className="mr-10">
                  <p className="text-white font-semibold">Date of Birth</p>   
                  <div className="bg-white flex items-center justify-center mt-3 space-x-4 w-60 h-14 p-2 rounded-xl">              
                        <DateSection/>
                  </div>
                </div>
                <div className="">
                  <p className="text-white font-semibold">Email Address</p>
                  <input type="text" className='w-60 h-14 p-2 mt-3 rounded-xl'/>
                </div>  
            </div>

            <div className="flex flex-col content-center items-center mt-10">
              <p className="text-white font-semibold">Address</p>
              <input type="text" style={{width:'54%'}} className="w-4/6 p-5 mt-3 rounded-xl h-14"/>
            </div>
            <button>
              Next Step
            </button>
          </div>
        </div>    
      </div>
    </form>
  )
}

export const StepTwo = () => {
  return (
    <form>
        <div>
            <Image src={Img} alt="form-image" 
            />
        </div>
        <div>
          {/* Step */}
      </div>
      <form>
        {/* content */}
        {/* button */}
      </form>
    </form>
  )
}

export const StepThree = () => {
  return (
    <form>
        <div>
            <Image src={Img} alt="form-image" 
            />
        </div>
        <div>
          {/* step */}
      </div>
      <form>
        {/* content */}
        {/* button */}
      </form>
    </form>
  )
}

export default function Home() {
  return (
    <Authentication>
      <div>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet"></link>
        </Head>
          <StepOne/>
          
        </div>
      </Authentication>
  )
}
